from selenium import webdriver
from selenium.webdriver.common.by import By
driver=webdriver.Chrome()
driver.maximize_window()
driver.get("https://parabank.parasoft.com/parabank/index.htm?ConnType=JDBC")
print(driver.title)
driver.find_element(By.XPATH,"//a[normalize-space()='Register']").click()
fstname=driver.find_element(By.XPATH,'//input[@id="customer.firstName"]')
fstname.send_keys("Shri")
lstname=driver.find_element(By.XPATH,'//input[@id="customer.lastName"]')
lstname.send_keys("S")
address=driver.find_element(By.XPATH,'//input[@id="customer.address.street"]')
address.send_keys("ABC")
city=driver.find_element(By.XPATH,'//input[@id="customer.address.city"]')
city.send_keys("ABCDEF")
state=driver.find_element(By.XPATH,'//input[@id="customer.address.state"]')
state.send_keys("TN")
zipcode=driver.find_element(By.XPATH,'//input[@id="customer.address.zipCode"]')
zipcode.send_keys("10")
phone=driver.find_element(By.XPATH,'//input[@id="customer.phoneNumber"]')
phone.send_keys("9876543210")
ssn=driver.find_element(By.XPATH,'//input[@id="customer.ssn"]')
ssn.send_keys("123456789235")
username=driver.find_element(By.XPATH,'//input[@id="customer.username"]')
username.send_keys("Demo1")
pswd=driver.find_element(By.XPATH,'//input[@id="customer.password"]')
pswd.send_keys("1234sh")
confirmps=driver.find_element(By.XPATH,'//input[@id="repeatedPassword"]')
confirmps.send_keys("1234sh")
driver.find_element(By.XPATH,"//input[@value='Register']").click()
bill=driver.find_element(By.XPATH,"//a[normalize-space()='Bill Pay']")
bill.click()
payname=driver.find_element(By.XPATH,'//input[@name="payee.name"]')
payname.send_keys("Demouser")
payadd=driver.find_element(By.XPATH,'//input[@name="payee.address.street"]')
payadd.send_keys("ABC")
city=driver.find_element(By.XPATH,'//input[@name="payee.address.city"]')
city.send_keys("BCA")
state=driver.find_element(By.XPATH,'//input[@name="payee.address.state"]')
state.send_keys("TN")
zpcode=driver.find_element(By.XPATH,'//input[@name="payee.address.zipCode"]')
zpcode.send_keys("7652")
phoneno=driver.find_element(By.XPATH,'//input[@name="payee.phoneNumber"]')
phoneno.send_keys("9875632101")
accno=driver.find_element(By.XPATH,'//input[@name="payee.accountNumber"]')
accno.send_keys("4321765")
verifyacc=driver.find_element(By.XPATH,'//input[@name="verifyAccount"]')
verifyacc.send_keys("4321765")
amt=driver.find_element(By.XPATH,'//input[@name="amount"]')
amt.send_keys("10")
tot=driver.find_element(By.XPATH,'//select/option[1]')
res=driver.find_element(By.XPATH,'//h1[text()="Bill Payment Complete"]')
assert res.text == "Bill Payment Complete"
print("Completed")



